// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	detectSystem: () => __TAURI_INVOKE<SystemInfo>("detect_system"),
};

/* Types */
export type AppInfo = {
	version: string,
	app_data_dir: string,
	log_dir: string,
};

/**
 *  Frontend-facing error shape. Stable across `AppError` refactors so the TS
 *  binding stays backwards-compatible.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type CpuFeatures = {
	avx2: boolean,
	avx512f: boolean,
};

export type CpuInfo = {
	vendor: string,
	brand: string,
	physical_cores: number,
	logical_cores: number,
	features: CpuFeatures,
};

export type MemoryInfo = {
	total_bytes: number,
	available_bytes: number,
};

export type OsFamily = "Windows" | "MacOs" | "Linux" | "Other";

export type OsInfo = {
	family: OsFamily,
	version: string | null,
	arch: string,
};

export type SystemInfo = {
	os: OsInfo,
	cpu: CpuInfo,
	memory: MemoryInfo,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

