// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	detectSystem: () => __TAURI_INVOKE<SystemInfo>("detect_system"),
	/**
	 *  GPU probe. Runs in `spawn_blocking` because NVML init and Vulkan instance
	 *  creation can each take a few hundred ms on cold driver load, and we don't
	 *  want to stall the Tauri IPC thread. `tauri::async_runtime` wraps tokio
	 *  so we don't need a direct tokio dep.
	 */
	detectGpu: () => __TAURI_INVOKE<GpuBackend>("detect_gpu"),
	/**
	 *  Pure backend-selection command. Takes already-detected `SystemInfo` and
	 *  `GpuBackend` from the frontend and returns the chosen inference backend
	 *  plus a short justification. Detection itself stays in `detect_system` /
	 *  `detect_gpu`; composing the three calls (with caching) is Fase 2.4.
	 */
	selectBackend: (system: SystemInfo, gpu: GpuBackend) => __TAURI_INVOKE<BackendChoice>("select_backend", { system, gpu }),
};

/* Types */
export type AppInfo = {
	version: string,
	app_data_dir: string,
	log_dir: string,
};

export type BackendChoice = {
	backend: InferenceBackend,
	reason: string,
};

/**
 *  Frontend-facing error shape. Stable across `AppError` refactors so the TS
 *  binding stays backwards-compatible.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type ComputeCapability = {
	major: number,
	minor: number,
};

export type CpuFeatures = {
	avx2: boolean,
	avx512f: boolean,
};

export type CpuInfo = {
	vendor: string,
	brand: string,
	physical_cores: number,
	logical_cores: number,
	features: CpuFeatures,
};

export type GpuBackend = { kind: "metal" } | { kind: "cuda"; name: string; vram_mb: number; compute_capability: ComputeCapability; uuid: string } | { kind: "vulkan"; vendor: VulkanVendor; vendor_id: number; name: string; vram_mb: number | null; device_type: VulkanDeviceType } | { kind: "none" };

export type InferenceBackend = "metal" | "cuda" | "vulkan" | "cpu";

export type MemoryInfo = {
	total_bytes: number,
	available_bytes: number,
};

export type OsFamily = "Windows" | "MacOs" | "Linux" | "Other";

export type OsInfo = {
	family: OsFamily,
	version: string | null,
	arch: string,
};

export type SystemInfo = {
	os: OsInfo,
	cpu: CpuInfo,
	memory: MemoryInfo,
};

export type VulkanDeviceType = "discrete" | "integrated" | "virtual" | "cpu" | "other";

export type VulkanVendor = "amd" | "intel" | "nvidia" | "other";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

