// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	detectSystem: () => __TAURI_INVOKE<SystemInfo>("detect_system"),
	/**
	 *  GPU probe. Runs in `spawn_blocking` because NVML init and Vulkan instance
	 *  creation can each take a few hundred ms on cold driver load, and we don't
	 *  want to stall the Tauri IPC thread. `tauri::async_runtime` wraps tokio
	 *  so we don't need a direct tokio dep.
	 */
	detectGpu: () => __TAURI_INVOKE<GpuBackend>("detect_gpu"),
	/**
	 *  Pure backend-selection command. Takes already-detected `SystemInfo` and
	 *  `GpuBackend` from the frontend and returns the chosen inference backend
	 *  plus a short justification. Kept exposed for dev tools; the standard
	 *  flow uses `detect_hardware` instead.
	 */
	selectBackend: (system: SystemInfo, gpu: GpuBackend) => __TAURI_INVOKE<BackendChoice>("select_backend", { system, gpu }),
	/**
	 *  Aggregate detection with a fingerprint-validated JSON cache. Returns
	 *  the full (system, gpu, choice) triple. When `force` is false, a cached
	 *  result is served if the host's CPU/RAM/OS fingerprint still matches;
	 *  when true, fresh detection runs unconditionally and the cache file is
	 *  overwritten. The blocking work (file I/O + GPU probe) is dispatched
	 *  to `spawn_blocking` so the Tauri IPC thread stays free.
	 */
	detectHardware: (force: boolean) => typedError<HardwareDetection, CommandError>(__TAURI_INVOKE("detect_hardware", { force })),
	// **TEMPORARY**: removed in Fase 4 once the catalog/download flow ships.
	devLoadModel: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("dev_load_model", { path })),
	startGeneration: (prompt: string, maxTokens: number | null) => typedError<string, CommandError>(__TAURI_INVOKE("start_generation", { prompt, maxTokens })),
	cancelGeneration: (generationId: string) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_generation", { generationId })),
	fetchCatalog: () => typedError<CatalogResponse, CommandError>(__TAURI_INVOKE("fetch_catalog")),
	fetchClassifiedCatalog: () => typedError<ClassifiedCatalogResponse, CommandError>(__TAURI_INVOKE("fetch_classified_catalog")),
	/** Start a resumable download; progress arrives via DownloadEvent. */
	startModelDownload: (model_id: string) => typedError<null, CommandError>(__TAURI_INVOKE("start_model_download", { model_id })),
	/** Cancel an in-flight download; .part file is preserved for resume. */
	cancelModelDownload: (model_id: string) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_model_download", { model_id })),
};

/** Events */
export const events = {
	generationEvent: makeEvent<GenerationEvent>("generation-event"),
	downloadEvent: makeEvent<DownloadEvent>("download-event"),
};

/* Types */
export type AppInfo = {
	version: string,
	app_data_dir: string,
	log_dir: string,
};

export type BackendChoice = {
	backend: InferenceBackend,
	reason: string,
};

export type Catalog = {
	schema_version: number,
	generated_at: string,
	models: ModelEntry[],
};

export type CatalogResponse = {
	catalog: Catalog,
	source: CatalogSource,
	fetched_at: string,
};

export type CatalogSource = "network" | "cache";

export type ClassifiedCatalogResponse = {
	models: ClassifiedModel[],
	source: CatalogSource,
	fetched_at: string,
	catalog_schema_version: number,
};

export type ClassifiedModel = {
	model: ModelEntry,
	tier: CompatibilityTier,
	gpu_offload: boolean,
};

export type CompatibilityTier = "Recommended" | "Viable" | "Heavy" | "NotSupported";

export type ChatTemplate = "Llama3" | "ChatML" | "Mistral" | "Gemma" | "Qwen" | "Phi3";

/**
 *  Frontend-facing error shape. Stable across `AppError` refactors so the TS
 *  binding stays backwards-compatible.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type ComputeCapability = {
	major: number,
	minor: number,
};

export type CpuFeatures = {
	avx2: boolean,
	avx512f: boolean,
};

export type CpuInfo = {
	vendor: string,
	brand: string,
	physical_cores: number,
	logical_cores: number,
	features: CpuFeatures,
};

export type DownloadEvent =
	| { type: "started"; model_id: string; total_bytes: number }
	| { type: "progress"; model_id: string; downloaded_bytes: number; total_bytes: number }
	| { type: "verifying"; model_id: string; hashed_bytes: number; total_bytes: number }
	| { type: "completed"; model_id: string; final_path: string }
	| { type: "failed"; model_id: string; kind: string; message: string }
	| { type: "cancelled"; model_id: string };

export type GenerationEvent = { type: "started"; generation_id: string } | { type: "token"; generation_id: string; text: string } | { type: "end"; generation_id: string; reason: StopReasonDto } | { type: "failed"; generation_id: string; kind: string; message: string } | { type: "cancelled"; generation_id: string };

export type GpuBackend = { kind: "metal" } | { kind: "cuda"; name: string; vram_mb: number; compute_capability: ComputeCapability; uuid: string } | { kind: "vulkan"; vendor: VulkanVendor; vendor_id: number; name: string; vram_mb: number | null; device_type: VulkanDeviceType } | { kind: "none" };

/**
 *  Wire type returned to the frontend. `from_cache` lets the UI show
 *  "Cached / Fresh"; `fingerprint` and `detected_at` are kept for debug
 *  surface. Distinct from [`CachedDetection`] (the on-disk shape) so the
 *  file format can evolve independently.
 */
export type HardwareDetection = {
	system: SystemInfo,
	gpu: GpuBackend,
	choice: BackendChoice,
	fingerprint: string,
	detected_at: string,
	from_cache: boolean,
};

export type InferenceBackend = "metal" | "cuda" | "vulkan" | "cpu";

export type MemoryInfo = {
	total_bytes: number,
	available_bytes: number,
};

export type ModelEntry = {
	id: string,
	name: string,
	publisher: string,
	description: string,
	license: string,
	tags: string[],
	url: string,
	filename: string,
	size_bytes: number,
	sha256: string,
	params_b: number,
	quantization: string,
	context_length: number,
	chat_template: ChatTemplate,
	min_ram_mb: number,
	recommended_ram_mb: number,
	min_vram_mb: number | null,
};

export type OsFamily = "Windows" | "MacOs" | "Linux" | "Other";

export type OsInfo = {
	family: OsFamily,
	version: string | null,
	arch: string,
};

export type StopReasonDto = "eog" | "max_tokens";

export type SystemInfo = {
	os: OsInfo,
	cpu: CpuInfo,
	memory: MemoryInfo,
};

export type VulkanDeviceType = "discrete" | "integrated" | "virtual" | "cpu" | "other";

export type VulkanVendor = "amd" | "intel" | "nvidia" | "other";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

